//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleStat.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_search_key
    {
        public int id { get; set; }
        public Nullable<int> year { get; set; }
        public string category { get; set; }
        public Nullable<int> no_vehicles { get; set; }
        public Nullable<int> distance { get; set; }
        public string key { get; set; }
    }
}
