//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleStat.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urban
    {
        public int id { get; set; }
        public string test_center { get; set; }
        public Nullable<sbyte> urban { get; set; }
    }
}
