//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleStat.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emission_test
    {
        public int id { get; set; }
        public string registration_no { get; set; }
        public Nullable<System.DateTime> test_datetime { get; set; }
        public string test_result { get; set; }
        public Nullable<int> registration_year { get; set; }
        public Nullable<int> province_code { get; set; }
        public Nullable<int> district_code { get; set; }
        public string make_by { get; set; }
        public string model { get; set; }
        public Nullable<int> manufacture_year { get; set; }
        public Nullable<int> number_of_cylinders { get; set; }
        public Nullable<int> vehicle_stroke { get; set; }
        public string fuel_type { get; set; }
        public Nullable<int> mileage { get; set; }
        public string vehicle_class { get; set; }
        public string test_location { get; set; }
    }
}
